import 'package:freezed_annotation/freezed_annotation.dart';

import 'diff_note_position.dart';
import 'user.dart';

part 'note.freezed.dart';
part 'note.g.dart';

/// A comment (note) on an issue or merge request.
///
/// A system note is generated by GitLab for events like "changed the
/// milestone"; [isSystem] lets the UI skip or de-emphasize those so a comment
/// thread stays readable.
@freezed
abstract class Note with _$Note {
  const factory Note({
    required int id,
    required String body,
    @JsonKey(name: 'system') @Default(false) bool isSystem,
    User? author,
    @JsonKey(name: 'created_at') DateTime? createdAt,
    @JsonKey(name: 'updated_at') DateTime? updatedAt,
    String? type,
    DiffNotePosition? position,
    bool? resolvable,
    bool? resolved,
    @JsonKey(name: 'resolved_by') User? resolvedBy,
    @JsonKey(name: 'resolved_at') DateTime? resolvedAt,
  }) = _Note;

  factory Note.fromJson(Map<String, dynamic> json) => _$NoteFromJson(json);
}
